### ISSUE TITLE
print() function does not work in list comprehension.

### ISSUE THREAD

**Issue by Mester** [rmotr/rmotr-sis#52]
The following code does not work (in class 2, assignment 6):

```
def print_members(a_list):
    [print(my_item) for my_item in a_list]
```

And gives the following syntax error:

```
  File "/usercode/file.py", line 13
    [print(my_item) for my_item in a_list]
         ^
SyntaxError: invalid syntax
```

It does however work when adding the import `from __future__ import print_function`

**Comment by santiagobasulto** [comment]
Ah, now I get it. This is not an issue. The system uses Python 2.7. In Py2 print is an expression, not a function. That's why you can't place it inside a list comprehension without importing Py3 print func; or defining your own print func:

```python
def my_print(elem):
    print(elem)

def print_members(a_list):
    [my_print(my_item) for my_item in a_list]
```

This is also an issue if you want to define a lambda in Py2. This will fail without importing future prints:

```python
print_plus_1 = lambda x: print(x + 1)
```
